### ISSUE TITLE
Consider adding extension.json for VSCode

### ISSUE THREAD

**Issue by TKDev7** [renegadevi/nuxt-boilerplate#2]
Consider adding extension.json for VSCode

**Comment by damevin** [comment]
@renegadevi what do you think about this ? 

I think best recommended extensions for project using nuxt 3, vue and typescript are those :

- [Nuxtr](https://marketplace.visualstudio.com/items?itemName=Nuxtr.nuxtr-vscode)
- [Volar](https://marketplace.visualstudio.com/items?itemName=Vue.volar)
- [Typescript Vue Plugin Volar](https://marketplace.visualstudio.com/items?itemName=Vue.vscode-typescript-vue-plugin)
- [Goto definition alias]( https://marketplace.visualstudio.com/items?itemName=antfu.goto-alias)
- [Tailwind CSS IntelliSense](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss)
- [Vue VsCode Snippets](https://marketplace.visualstudio.com/items?itemName=sdras.vue-vscode-snippets)
- [i18n ally](https://marketplace.visualstudio.com/items?itemName=Lokalise.i18n-ally)

Do not hesitate to add/remove according to your opinion 😄 
I'll make a PR tomorrow morning 💪

**Comment by renegadevi** [comment]
I originally had a `.vscode/settings.json` but I excluded it. Didn't know if it added much. 

**settings.json**
```json
{
  "files.associations": {
    "*.css": "tailwindcss"
  },
  "editor.quickSuggestions": {
    "strings": true
  },
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.tabSize": 2
  },
  "[vue]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "files.trimTrailingWhitespace": true,
  "npm.packageManager": "pnpm",
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "css.lint.unknownAtRules": "ignore",
  "tailwindCSS.includeLanguages": {
    "html": "html",
    "javascript": "javascript",
    "vue": "vue",
    "css": "css"
  },
  "tailwindCSS.emmetCompletions": true,
  "i18n-ally.localesPaths": [
    "locales"
  ]
}
```

### These are the plugins I recommend:

- [ESLint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
- [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)
- [Prettier ESLint](https://marketplace.visualstudio.com/items?itemName=rvest.vs-code-prettier-eslint)
- [Pretty TypeScript Errors](https://marketplace.visualstudio.com/items?itemName=yoavbls.pretty-ts-errors)
- [TypeScript Vue Plugin (Volar)](https://marketplace.visualstudio.com/items?itemName=Vue.vscode-typescript-vue-plugin)
- [Vue Language Features (Volar)](https://marketplace.visualstudio.com/items?itemName=Vue.volar)
- [Tailwind CSS IntelliSense](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss)

### These are nice extras

- [Goto definition alias](https://marketplace.visualstudio.com/items?itemName=antfu.goto-alias)
- [Nuxt (unofficial)](https://marketplace.visualstudio.com/items?itemName=cpreston321.nuxt-vscode)
- [Nuxtr](https://marketplace.visualstudio.com/items?itemName=Nuxtr.nuxtr-vscode)
- [i18n Ally](https://marketplace.visualstudio.com/items?itemName=Lokalise.i18n-ally)
- [Tailwind Shades](https://marketplace.visualstudio.com/items?itemName=bourhaouta.tailwindshades)
- [Vue VSCode Snippets](https://marketplace.visualstudio.com/items?itemName=sdras.vue-vscode-snippets)
